# Generated by Django 3.0.6 on 2020-05-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='youTubeChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('creator', models.CharField(max_length=20)),
                ('preference', models.IntegerField(max_length=20)),
                ('live', models.BooleanField(max_length=20)),
                ('subscribers', models.IntegerField(max_length=20)),
            ],
        ),
    ]
