# Generated by Django 3.0.6 on 2020-05-19 11:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('makePage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubechannel',
            name='link1',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='youtubechannel',
            name='link2',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='youtubechannel',
            name='link3',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
