# Generated by Django 3.0.6 on 2020-05-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makePage', '0002_auto_20200519_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubechannel',
            name='live',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='youtubechannel',
            name='preference',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='youtubechannel',
            name='subscribers',
            field=models.IntegerField(),
        ),
    ]
